# Generated by Django 5.2.17 on 2026-10-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="locale",
            field=models.CharField(
                blank=True,
                choices=[("ar", "Arabic"), ("en", "English")],
                default="",
                max_length=2,
            ),
        ),
    ]
