# Generated by Django 5.2.17 on 2026-09-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_businessprofile_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
