# Generated by Django 5.2.17 on 2026-09-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_businessprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="follower_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
