# Generated by Django 5.2.17 on 2026-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0004_businessprofile_follower_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
