# Generated by Django 5.2.17 on 2026-09-26 10:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_businessprofile_is_featured"),
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="businessprofile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="business_search_vector_gin"
            ),
        ),
    ]
