# Generated by Django 5.2.17 on 2026-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_alter_businessprofile_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
