# Generated by Django 5.2.17 on 2026-10-03 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0008_businessprofile_average_rating_and_more"),
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="businessprofile",
            index=models.Index(
                fields=["category", "city"], name="biz_category_city_idx"
            ),
        ),
    ]
