# Generated by Django 5.2.17 on 2026-09-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="chat/media/"),
        ),
        migrations.AddField(
            model_name="message",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[("image", "Image"), ("video", "Video")],
                default="",
                max_length=10,
            ),
        ),
    ]
