# Generated by Django 5.2.17 on 2026-09-29 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_media"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="shared_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="shared_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("shared_content_type__isnull", True),
                        ("shared_object_id__isnull", True),
                    ),
                    models.Q(
                        ("shared_content_type__isnull", False),
                        ("shared_object_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="message_shared_ref_both_or_neither",
            ),
        ),
    ]
