# Generated by Django 5.2.17 on 2026-09-22 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0003_businessprofile_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("media", models.FileField(upload_to="stories/media/")),
                ("published_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stories",
                        to="businesses.businessprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "status", "expires_at"],
                        name="story_biz_status_exp_idx",
                    )
                ],
            },
        ),
    ]
