# Generated by Django 5.2.17 on 2026-10-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0009_p101_composite_indexes"),
        ("stories", "0003_storyview"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["business", "status", "created_at"],
                name="story_biz_status_created_idx",
            ),
        ),
    ]
