# Generated by Django 5.2.17 on 2026-09-13 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_moderate_content", "Can moderate content"),
                    ("can_manage_categories", "Can manage categories"),
                    ("can_ban_users", "Can ban users"),
                    ("can_manage_notifications", "Can manage notifications"),
                    ("can_manage_monetization", "Can manage monetization"),
                ]
            },
        ),
    ]
