# Generated by Django 5.2.17 on 2026-09-13 02:43
"""
Part P-019: seed the three default authorization Groups.

Assigning a user to one of these Groups grants the matching capability
bundle immediately, with no code change (Django's ``has_perm`` reads
Group-assigned permissions live) — this is the whole point of the
permission-based framework core/permissions.py's ``HasCapability``
builds on.

Group -> permission mapping (locked contract; do not change silently —
see core/permissions.py and accounts/models.py's Meta.permissions):

    Moderator  -> can_moderate_content
    Admin      -> can_moderate_content, can_manage_categories,
                  can_ban_users, can_manage_notifications,
                  can_manage_monetization
    SuperAdmin -> same permission set as Admin

SuperAdmin note: "manage other admins" capability is deliberately NOT a
custom permission here. Per this part's own scope, that's better
expressed via Django's built-in ``is_superuser`` flag (which already
implicitly grants every permission, and is what Django Admin's own
staff-user management screens key off) than via a redundant custom
flag. Putting a user in the SuperAdmin group only grants the Admin
capability bundle by name (useful for HasCapability checks and for
Django Admin's Group listing); actually elevating someone to
"can manage other admins" still requires separately setting
``is_superuser=True`` on that user (e.g. via `manage.py createsuperuser`
or the Django Admin "Permissions" section) — this migration does not
and cannot do that for you, since it has no specific user to act on.

Real bug found and fixed during this part's own validation (not just
assumed): the ``Permission`` rows for a model's ``Meta.permissions`` are
normally created by Django's ``post_migrate`` signal
(``django.contrib.auth.management.create_permissions``), which only
fires ONCE, after every migration in the same ``migrate`` invocation has
already applied — not incrementally after each individual migration.
Running ``manage.py migrate`` as several separate commands (as this
part's own manual/real-machine validation did) hides this, because each
invocation's own ``post_migrate`` fires before the next one starts. But
`pytest-django` builds the test database with a single ``migrate``
invocation covering 0001 -> 0002 -> 0003 in one go, so when 0003 (this
file) tried to query for the ``can_moderate_content`` etc. Permission
rows, they did not exist yet -> a real ``RuntimeError`` from this
migration's own sanity check, confirmed via a live `pytest` run, not
hypothesized. The fix: call ``create_permissions`` explicitly, against
the CURRENT (non-historical) app registry, before querying — this forces
the rows to exist regardless of how many `migrate` invocations are
involved. Any future part adding a data migration that reads a custom
``Meta.permissions`` codename must do the same, or hit this exact
failure the first time a fresh database is built in one shot (exactly
what `pytest`/CI/a fresh clone's first `migrate` all do).
"""

from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations

MODERATOR_PERMS = ["can_moderate_content"]

ADMIN_PERMS = [
    "can_moderate_content",
    "can_manage_categories",
    "can_ban_users",
    "can_manage_notifications",
    "can_manage_monetization",
]

SUPERADMIN_PERMS = ADMIN_PERMS

GROUP_PERMS = {
    "Moderator": MODERATOR_PERMS,
    "Admin": ADMIN_PERMS,
    "SuperAdmin": SUPERADMIN_PERMS,
}


def seed_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    User = apps.get_model("accounts", "User")

    # Force the Meta.permissions rows to exist right now, rather than
    # waiting for the post_migrate signal (which hasn't fired yet at
    # this point in a single fresh `migrate` run — see the module
    # docstring's "Real bug found and fixed" note above). Uses the
    # CURRENT global app registry (not the historical `apps` argument)
    # because create_permissions reads permissions off the real,
    # present-day accounts.User.Meta — which already has them, since
    # this migration's own dependency graph runs after 0002 in the
    # source code, even though the *rows* aren't created until now.
    create_permissions(global_apps.get_app_config("accounts"), verbosity=0)

    user_content_type = ContentType.objects.get_for_model(User)

    for group_name, codenames in GROUP_PERMS.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        permissions = Permission.objects.filter(
            content_type=user_content_type,
            codename__in=codenames,
        )
        # Sanity check: every codename must resolve to a real Permission
        # row (created by the previous migration, 0002). If this ever
        # fires, a codename was renamed/removed without updating this
        # migration — fail loudly rather than silently seeding a group
        # with fewer permissions than intended.
        if permissions.count() != len(codenames):
            found = set(permissions.values_list("codename", flat=True))
            missing = set(codenames) - found
            raise RuntimeError(
                f"Cannot seed group '{group_name}': missing permission "
                f"codename(s) {sorted(missing)} on accounts.User. Check "
                "accounts/models.py's Meta.permissions and this "
                "migration stay in sync."
            )
        group.permissions.set(permissions)


def unseed_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=GROUP_PERMS.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options"),
    ]

    operations = [
        migrations.RunPython(seed_groups, unseed_groups),
    ]