# Generated by Django 5.2.17 on 2026-09-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_seed_authorization_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
