# Generated by Django 5.2.17 on 2026-09-20 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('fast_path', 'Fast path')], default='normal', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_queue_entries', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Moderation queue entry',
                'verbose_name_plural': 'Moderation queue entries',
                'db_table': 'moderation_moderationqueue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='moderation__content_095806_idx'), models.Index(fields=['status'], name='moderation__status_731a97_idx')],
            },
        ),
    ]
