# Generated by Django 5.2.17 on 2026-09-20 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('queue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='moderation.moderationqueue')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation log entry',
                'verbose_name_plural': 'Moderation log entries',
                'db_table': 'moderation_moderationlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
