# Generated by Django 5.2.17 on 2026-09-21 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_businessprofile_phone_number'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('caption', models.TextField()),
                ('video', models.FileField(upload_to='reels/videos/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='reels/thumbnails/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reels', to='businesses.businessprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['business'], name='content_reel_business_idx')],
            },
        ),
    ]
