# Generated by Django 5.2.17 on 2026-09-21 10:06

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_reel'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reel',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
