# Generated by Django 5.2.17 on 2026-09-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_post_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="reel",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
