# Generated by Django 5.2.17 on 2026-09-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_reel_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
