# Generated by Django 5.2.17 on 2026-09-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_post_comments_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="reel",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
