# Generated by Django 5.2.17 on 2026-09-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_reel_comments_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
