# Generated by Django 5.2.17 on 2026-09-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_post_shares_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="reel",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
