# Generated by Django 5.2.17 on 2026-10-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0009_p101_composite_indexes"),
        ("content", "0009_reel_shares_count"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["business", "status", "created_at"],
                name="post_biz_status_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(
                fields=["business", "status", "created_at"],
                name="reel_biz_status_created_idx",
            ),
        ),
    ]
