# Generated by Django 5.2.17 on 2026-09-30 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chat_notifications_enabled", models.BooleanField(default=True)),
                ("moderation_notifications_enabled", models.BooleanField(default=True)),
                ("social_notifications_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification preference",
                "verbose_name_plural": "Notification preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("chat_message", "Chat message"),
                            ("moderation_approved", "Moderation approved"),
                            ("moderation_rejected", "Moderation rejected"),
                            ("new_follower", "New follower"),
                            ("comment_on_content", "Comment on content"),
                            ("new_like", "New like"),
                            ("new_share", "New share"),
                            ("new_rating", "New rating"),
                            ("system_announcement", "System announcement"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "deep_link_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("business_profile", "Business profile"),
                            ("post_detail", "Post detail"),
                            ("reel_detail", "Reel detail"),
                            ("product_detail", "Product detail"),
                            ("chat_thread", "Chat thread"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notif_recipient_created_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"], name="notif_recipient_read_idx"
                    ),
                ],
            },
        ),
    ]
