# Generated by Django 5.2.17 on 2026-10-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_backfill_notification_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="params",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
