# Generated by Django 5.2.17 on 2026-09-26 10:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0006_businessprofile_search_vector_and_more"),
        ("categories", "0001_initial"),
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="products_search_vector_gin"
            ),
        ),
    ]
