# Generated by Django 5.2.17 on 2026-09-26 11:04

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_search_vector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
